// Generated by https://quicktype.io

export interface PlacesResponses {
    type: string;
    query: string[];
    features: Feature[];
    attribution: string;
}

export interface Feature {
    id: string;
    type: string;
    place_type: string[];
    relevance: number;
    properties: Properties;
    text_es: string;
    place_name_es: string;
    text: string;
    place_name: string;
    center: number[];
    geometry: Geometry;
    context: Context[];
}

export interface Context {
    id: ID;
    text_es: Text;
    text: Text;
    wikidata?: Wikidata;
    language_es?: Language;
    language?: Language;
    short_code?: ShortCode;
}

export enum ID {
    Country8715 = "country.8715",
    Place21989387 = "place.21989387",
    Postcode16887307 = "postcode.16887307",
    Region115723 = "region.115723",
}

export enum Language {
    Es = "es",
}

export enum ShortCode {
    Ar = "ar",
    ArQ = "AR-Q",
}

export enum Text {
    Argentina = "Argentina",
    ProvinciaDeNeuquén = "Provincia de Neuquén",
    Q8370 = "Q8370",
    SANMartínDeLosAndes = "San Martín de los Andes",
}

export enum Wikidata {
    Q1019152 = "Q1019152",
    Q414 = "Q414",
    Q44800 = "Q44800",
}

export interface Geometry {
    coordinates: number[];
    type: string;
}

export interface Properties {
    foursquare: string;
    landmark: boolean;
    address?: string;
    category: string;
}
